import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import EviteFilas from "public/images/eviteFilas.png"
import ReacregueAqui from "public/images/recarregueAqui.png"
import IconeTCC from "public/images/icon.png"
import { ButtonComponent } from '@/components/button'
import Spacer from '@/components/spacer'
import styles from '@/styles/home.module.scss'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${inter.className} ${styles.main}`}>
				<Image src={EviteFilas} alt='Evite Filas!' className={styles.title} />
				<Image src={ReacregueAqui} alt='Recarregue sua carteirinha aqui!' className={styles.subtitle} />
				<Image src={IconeTCC} alt='Recarregue sua carteirinha aqui!' className={styles.icon} />
				<Spacer height='20px' />
				<ButtonComponent lineHeight="20px" fontSize='16px' href='/dados' text='aproxime sua carteirinha do sensor' />

			</main>
		</>
	)
}
